print("##############################")
print("#                            #")
print("#    Achmad Reihan Alfaiz    #")
print("#       24108172100019       #")
print("#                            #")
print("##############################")
